[phases.setup]
nixPkgs = ["dotnet-sdk_10"]

[phases.build]
cmds = [
    "cd civ5hype",
    "dotnet restore",
    "dotnet publish -c Release -o out"
]

[start]
cmd = "cd civ5hype/out && dotnet civ5hype.dll --urls http://0.0.0.0:$PORT"

